#!/usr/bin/env bash
set -euo pipefail
cd /home/DM24/workspace/Time_Series_Forecasting/SC_FTMixer_SDE_Unified

# pred_len=96, MSE=0.163089, MAE=0.243260
python3 -u main_sde.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTm2.csv \
  --model_id ETTm2_96_96_ExpBest \
  --model SC_FTMixer_SDE_Unified \
  --data ETTm2 \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 96 \
  --freq t \
  --enc_in 7 \
  --d_model 32 \
  --d_ff 64 \
  --e_layers 1 \
  --n_heads 1 \
  --dropout 0 \
  --batch_size 1024 \
  --learning_rate 0.005 \
  --train_epochs 100 \
  --patience 10 \
  --lradj cosine_warmup \
  --des ExpBest_ETTm2_96 \
  --itr 1 \
  --num_workers 2 \
  --use_sde 1 \
  --sde_phase_mode day_slot \
  --sde_cycle_len 96 \
  --sde_slots_per_hour 4 \
  --sde_calendar_gate_init 2.0 \
  --sde_hidden 256 \
  --sde_rec_weight 0.25 \
  --sde_spectral_weight 0.75

# pred_len=192, MSE=0.227569, MAE=0.286067
python3 -u main_sde.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTm2.csv \
  --model_id ETTm2_96_192_ExpBest \
  --model SC_FTMixer_SDE_Unified \
  --data ETTm2 \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 192 \
  --freq t \
  --enc_in 7 \
  --d_model 32 \
  --d_ff 64 \
  --e_layers 1 \
  --n_heads 1 \
  --dropout 0 \
  --batch_size 1024 \
  --learning_rate 0.005 \
  --train_epochs 100 \
  --patience 10 \
  --lradj cosine_warmup \
  --des ExpBest_ETTm2_192 \
  --itr 1 \
  --num_workers 2 \
  --use_sde 1 \
  --sde_phase_mode day_slot \
  --sde_cycle_len 96 \
  --sde_slots_per_hour 4 \
  --sde_calendar_gate_init 2.0 \
  --sde_hidden 192 \
  --sde_rec_weight 0.25 \
  --sde_spectral_weight 0.75

# pred_len=336, MSE=0.284950, MAE=0.323495
python3 -u main_sde.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTm2.csv \
  --model_id ETTm2_96_336_ExpBest \
  --model SC_FTMixer_SDE_Unified \
  --data ETTm2 \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 336 \
  --freq t \
  --enc_in 7 \
  --d_model 32 \
  --d_ff 64 \
  --e_layers 1 \
  --n_heads 1 \
  --dropout 0 \
  --batch_size 1024 \
  --learning_rate 0.005 \
  --train_epochs 100 \
  --patience 10 \
  --lradj cosine_warmup \
  --des ExpBest_ETTm2_336 \
  --itr 1 \
  --num_workers 2 \
  --use_sde 1 \
  --sde_phase_mode day_slot \
  --sde_cycle_len 96 \
  --sde_slots_per_hour 4 \
  --sde_calendar_gate_init 2.0 \
  --sde_hidden 256 \
  --sde_rec_weight 0.25 \
  --sde_spectral_weight 0.75

# pred_len=720, MSE=0.381264, MAE=0.381834
python3 -u main_sde.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTm2.csv \
  --model_id ETTm2_96_720_ExpBest \
  --model SC_FTMixer_SDE_Unified \
  --data ETTm2 \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 720 \
  --freq t \
  --enc_in 7 \
  --d_model 32 \
  --d_ff 64 \
  --e_layers 1 \
  --n_heads 1 \
  --dropout 0 \
  --batch_size 1024 \
  --learning_rate 0.005 \
  --train_epochs 100 \
  --patience 10 \
  --lradj cosine_warmup \
  --des ExpBest_ETTm2_720 \
  --itr 1 \
  --num_workers 2 \
  --use_sde 1 \
  --sde_phase_mode day_slot \
  --sde_cycle_len 96 \
  --sde_slots_per_hour 4 \
  --sde_calendar_gate_init 2.0 \
  --sde_hidden 256 \
  --sde_rec_weight 0.25 \
  --sde_spectral_weight 0.75
