#!/usr/bin/env bash
set -euo pipefail
cd /home/DM24/workspace/Time_Series_Forecasting/SC_FTMixer_SDE_Unified

# pred_len=96, MSE=0.149704, MAE=0.190888
python3 -u main_sde.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/weather/ \
  --data_path weather.csv \
  --model_id Weather_96_96_ExpBest \
  --model SC_FTMixer_SDE_Unified \
  --data custom \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 96 \
  --freq t \
  --enc_in 21 \
  --d_model 32 \
  --d_ff 64 \
  --e_layers 1 \
  --n_heads 1 \
  --dropout 0 \
  --batch_size 1024 \
  --learning_rate 0.005 \
  --train_epochs 100 \
  --patience 10 \
  --lradj cosine_warmup \
  --des ExpBest_Weather_96 \
  --itr 1 \
  --num_workers 2 \
  --use_sde 1 \
  --sde_phase_mode day_slot \
  --sde_cycle_len 144 \
  --sde_slots_per_hour 6 \
  --sde_calendar_gate_init 2.0 \
  --sde_hidden 256 \
  --sde_rec_weight 0.50 \
  --sde_spectral_weight 0.50

# pred_len=192, MSE=0.201087, MAE=0.239281
python3 -u main_sde.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/weather/ \
  --data_path weather.csv \
  --model_id Weather_96_192_ExpBest \
  --model SC_FTMixer_SDE_Unified \
  --data custom \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 192 \
  --freq t \
  --enc_in 21 \
  --d_model 32 \
  --d_ff 64 \
  --e_layers 1 \
  --n_heads 1 \
  --dropout 0 \
  --batch_size 1024 \
  --learning_rate 0.005 \
  --train_epochs 100 \
  --patience 10 \
  --lradj cosine_warmup \
  --des ExpBest_Weather_192 \
  --itr 1 \
  --num_workers 2 \
  --use_sde 1 \
  --sde_phase_mode day_slot \
  --sde_cycle_len 144 \
  --sde_slots_per_hour 6 \
  --sde_calendar_gate_init 2.0 \
  --sde_hidden 256 \
  --sde_rec_weight 0.25 \
  --sde_spectral_weight 0.75

# pred_len=336, MSE=0.258547, MAE=0.282614
python3 -u main_sde.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/weather/ \
  --data_path weather.csv \
  --model_id Weather_96_336_ExpBest \
  --model SC_FTMixer_SDE_Unified \
  --data custom \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 336 \
  --freq t \
  --enc_in 21 \
  --d_model 32 \
  --d_ff 64 \
  --e_layers 1 \
  --n_heads 1 \
  --dropout 0 \
  --batch_size 1024 \
  --learning_rate 0.005 \
  --train_epochs 100 \
  --patience 10 \
  --lradj cosine_warmup \
  --des ExpBest_Weather_336 \
  --itr 1 \
  --num_workers 2 \
  --use_sde 1 \
  --sde_phase_mode day_slot \
  --sde_cycle_len 144 \
  --sde_slots_per_hour 6 \
  --sde_calendar_gate_init 2.0 \
  --sde_hidden 256 \
  --sde_rec_weight 0.25 \
  --sde_spectral_weight 0.75

# pred_len=720, MSE=0.340136, MAE=0.339441
python3 -u main_sde.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/weather/ \
  --data_path weather.csv \
  --model_id Weather_96_720_ExpBest \
  --model SC_FTMixer_SDE_Unified \
  --data custom \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 720 \
  --freq t \
  --enc_in 21 \
  --d_model 32 \
  --d_ff 64 \
  --e_layers 1 \
  --n_heads 1 \
  --dropout 0 \
  --batch_size 1024 \
  --learning_rate 0.005 \
  --train_epochs 100 \
  --patience 10 \
  --lradj cosine_warmup \
  --des ExpBest_Weather_720 \
  --itr 1 \
  --num_workers 2 \
  --use_sde 1 \
  --sde_phase_mode day_slot \
  --sde_cycle_len 144 \
  --sde_slots_per_hour 6 \
  --sde_calendar_gate_init 2.0 \
  --sde_hidden 256 \
  --sde_rec_weight 0.25 \
  --sde_spectral_weight 0.75
